server:
    SERVICE_NAME : "ssx"
    API_ROOT : "/ispyb/api/v1/ssx"
    SQLALCHEMY_DATABASE_URI : "mysql://mxuser:mxpass@localhost/ispyb_ssx"

    AUTH:
    [
      {
        AUTH_MODULE: "pyispyb.app.extensions.auth.KeycloakAuthentication",
        AUTH_CLASS: "KeycloakAuthentication",
      }
    ]
    MASTER_TOKEN : "MasterToken"