server:
    SERVICE_NAME: "core"
    API_ROOT: "/ispyb/api/v1"
    SQLALCHEMY_DATABASE_URI: "mysql://mxuser:mxpass@localhost/pydb_test"

    AUTH:
        - keycloak:
              AUTH_MODULE: "pyispyb.app.extensions.auth.KeycloakDBRolesAuthentication"
              AUTH_CLASS: "KeycloakDBRolesAuthentication"
        - ldap:
              AUTH_MODULE: "pyispyb.app.extensions.auth.LdapAuthentication"
              AUTH_CLASS: "LdapAuthentication"
        - dummy: # /!\/!\/!\ ONLY USE FOR TESTS /!\/!\/!\
              AUTH_MODULE: "pyispyb.app.extensions.auth.DummyAuthentication"
              AUTH_CLASS: "DummyAuthentication"

    KEYCLOAK_SERVER_URL: "your_server"
    KEYCLOAK_CLIENT_ID: "your_client"
    KEYCLOAK_REALM_NAME: "your_realm"
    KEYCLOAK_CLIENT_SECRET_KEY: "your_secret"

    LDAP_URI: "ldap://your_ldap"
    LDAP_BASE_INTERNAL: "ou=People,dc=esrf,dc=fr"
    LDAP_BASE_EXTERNAL: "ou=Pxwebgroups,dc=esrf,dc=fr"

    SECRET_KEY: "CHANGEME"
