server:
    SERVICE_NAME : "core"
    API_ROOT : "/ispyb/api/v1"
    SQLALCHEMY_DATABASE_URI : "mysql://mxuser:mxpass@localhost/pydb_test"

    AUTH:
    [
      {
        AUTH_MODULE: "pyispyb.app.extensions.auth.KeycloakAuthentication",
        AUTH_CLASS: "KeycloakAuthentication",
      }
    ]
    
    MASTER_TOKEN : "MasterToken"

authorization_rules:
    proposals : {
        "get": ["manager", "admin", "user"],
        "post": ["manager", "admin"]
    }