server:
    SERVICE_NAME : "em"
    API_ROOT : "/ispyb/api/v1/em"
    SQLALCHEMY_DATABASE_URI : "mysql://mxuser:mxpass@localhost/pydb_test"

    AUTH:
    [
      {
        AUTH_MODULE: "pyispyb.app.extensions.auth.KeycloakAuthentication",
        AUTH_CLASS: "KeycloakAuthentication",
      }
    ]
